#include "servos.h"

extern TIM_HandleTypeDef htim3;




void turnRight()
{
	//if(htim3.Instance->CCR1>=SERVO_MIN_PWM+SERVO_ANGLE_VARIATION)
		htim3.Instance->CCR1-=SERVO_ANGLE_VARIATION;

	//if(htim3.Instance->CCR2>=SERVO_MIN_PWM+SERVO_ANGLE_VARIATION)
		htim3.Instance->CCR2-=SERVO_ANGLE_VARIATION;

	//if(htim3.Instance->CCR3<=SERVO_MAX_PWM-SERVO_ANGLE_VARIATION)
		htim3.Instance->CCR3+=SERVO_ANGLE_VARIATION;

	//if(htim3.Instance->CCR4<=SERVO_MAX_PWM-SERVO_ANGLE_VARIATION)
		htim3.Instance->CCR4+=SERVO_ANGLE_VARIATION;
}

void turnLeft()
{
	//if(htim3.Instance->CCR1<=SERVO_MAX_PWM-SERVO_ANGLE_VARIATION)
		htim3.Instance->CCR1+=SERVO_ANGLE_VARIATION;

	//if(htim3.Instance->CCR2<=SERVO_MAX_PWM-SERVO_ANGLE_VARIATION)
		htim3.Instance->CCR2+=SERVO_ANGLE_VARIATION;

	//if(htim3.Instance->CCR3>=SERVO_MIN_PWM+SERVO_ANGLE_VARIATION)
		htim3.Instance->CCR3-=SERVO_ANGLE_VARIATION;

	//if(htim3.Instance->CCR4>=SERVO_MIN_PWM+SERVO_ANGLE_VARIATION)
		htim3.Instance->CCR4-=SERVO_ANGLE_VARIATION;

}
void dive()
{
	//if(htim3.Instance->CCR1>=SERVO_MIN_PWM+SERVO_ANGLE_VARIATION)
		htim3.Instance->CCR1-=SERVO_ANGLE_VARIATION;
	//if(htim3.Instance->CCR2<=SERVO_MAX_PWM-SERVO_ANGLE_VARIATION)
		htim3.Instance->CCR2+=SERVO_ANGLE_VARIATION;
	//if(htim3.Instance->CCR3>=SERVO_MIN_PWM+SERVO_ANGLE_VARIATION)
		htim3.Instance->CCR3-=SERVO_ANGLE_VARIATION;
	//if(htim3.Instance->CCR4<=SERVO_MAX_PWM-SERVO_ANGLE_VARIATION)
		htim3.Instance->CCR4+=SERVO_ANGLE_VARIATION;

}
void surface()
{
	//if(htim3.Instance->CCR1<=SERVO_MAX_PWM-SERVO_ANGLE_VARIATION)
		htim3.Instance->CCR1+=SERVO_ANGLE_VARIATION;
	//if(htim3.Instance->CCR2>=SERVO_MIN_PWM+SERVO_ANGLE_VARIATION)
		htim3.Instance->CCR2-=SERVO_ANGLE_VARIATION;
	//if(htim3.Instance->CCR3<=SERVO_MAX_PWM-SERVO_ANGLE_VARIATION)
		htim3.Instance->CCR3+=SERVO_ANGLE_VARIATION;
	//if(htim3.Instance->CCR4>=SERVO_MIN_PWM+SERVO_ANGLE_VARIATION)
		htim3.Instance->CCR4-=SERVO_ANGLE_VARIATION;
}
void neutralRudders()
{
	htim3.Instance->CCR1=SERVO_CENTER_PWM;
	htim3.Instance->CCR2=SERVO_CENTER_PWM;
	htim3.Instance->CCR3=SERVO_CENTER_PWM;
	htim3.Instance->CCR4=SERVO_CENTER_PWM;

}
